### ISSUE TITLE
eksctl Compatibility? 

### ISSUE THREAD

**Issue by safakozdek** [gitpod-io/self-hosted#26]
Can I use the given descriptions at https://www.gitpod.io/docs/self-hosted/latest/install/install-on-kubernetes/  for AWS EKS. I am trying to deploy the self-hosted repository using EKS but is it even possible?

**Comment by JesterOrNot** [comment]
Hello @safakozdek, AWS for Gitpod-Self-Hosted is currently in the works right now, while (in my testing) it is possible to deploy to EKS. Please stay tuned for an official install script though. Also, be sure to have https for some reason Gitpod-Self-Hosted won't work without it in EKS.

**Comment by safakozdek** [comment]
Thanks for the response.
