### ISSUE TITLE
Redirected to gitpod.io when I access the hosted domain

### ISSUE THREAD

**Issue by jagtesh** [gitpod-io/self-hosted#28]
I've gone through all the steps diligently at least 3 times on different kubernetes vanilla clusters. Every time I accessed the domain hosting my installation, I'd get redirected to https://gitpod.io.

I finally gave up thinking I'm doing something wrong. So this time, I installed on GCP with the automated setup, and yet - I get redirected to gitpod.io again. This is despite having the domain clearly set up in values.yml (along with GitHub oauth set up).

Not sure if gitpod has it's own domain hard-coded somewhere? I am actually surprised no one else has encountered this yet. I'd really appreciate any inputs.

**Comment by JesterOrNot** [comment]
This is a known issue, glad this is being tracked though Try to go to `<your-domain.com>/login` and see if after you have logged in if the problem persists.

**Comment by jagtesh** [comment]
I'll try that today. Thanks for confirming that!

**Comment by asthomasdk** [comment]
I am also seeing this - trying to run on a civo k3s cluster.

**Comment by asthomasdk** [comment]
Trying to access https://<my domain>/login, I get a blank screen - so not seeing my configured Gitlab.com Oauth login - and I get a load of websocket errors:  
```
wss://www.<my domain>/api/gitpod' failed: Error during WebSocket handshake: Unexpected response code: 302
```

**Comment by JesterOrNot** [comment]
@asthomasdk, in my experience this is usually due to a misconfiguration in the values file can you post your `values.yaml` file? Maybe you missed something, also are all the pods running/healthy?

**Comment by meysholdt** [comment]
Workaround1: 
Open `https://<your-gitpod-domain>/workspaces/`

Workaround1:
Set the following in your `values.yaml`:
```yaml
gitpod:
  branding:
    homepage: https://mydomain/
    redirectUrlIfNotAuthenticated: /workspaces/ # value of `homepage` is default
    redirectUrlAfterLogout: https://mydomain/
```

**Comment by jagtesh** [comment]
The workarounds (both /login and going to /workspaces) worked for me.
